# Site settings
title: Christian E. Lysel
email: webmaster@lysel.net
description: "Helt privat"
#baseurl: "http://christian.lysel.net/"
#url: http://christian.lysel.net
twitter_username: clysel
github_username:  clysel
facebook_username:  clysel

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
paginate: 15
#exclude: ["node_modules"]

gems:
  - jekyll-sitemap


