# Site settings
title: Christian E. Lysel
email: webmaster@lysel.net
description: "Christian privat"
baseurl: "http://christian.lysel.net"
url: "http://christian.lysel.net"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
