# Site settings
title: Christian E. Lysel
email: webmaster@lysel.net
description: "Helt privat"
baseurl: ""
url: "http://christian.lysel.net"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
